# Generated by Django 6.0.3 on 2026-03-30 10:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('ic_number', models.CharField(max_length=12, unique=True)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('belt_rank', models.CharField(choices=[('white', 'White Belt'), ('yellow_1', 'Yellow Belt 1'), ('yellow_2', 'Yellow Belt 2'), ('green_1', 'Green Belt 1'), ('green_2', 'Green Belt 2'), ('blue_1', 'Blue Belt 1'), ('blue_2', 'Blue Belt 2'), ('red_1', 'Red Belt 1'), ('red_2', 'Red Belt 2'), ('black_1', 'Black Belt 1st DAN'), ('black_2', 'Black Belt 2nd DAN'), ('black_3', 'Black Belt 3rd DAN'), ('black_4', 'Black Belt 4th DAN'), ('black_5', 'Black Belt 5th DAN'), ('black_6', 'Black Belt 6th DAN'), ('black_7', 'Black Belt 7th DAN'), ('black_8', 'Black Belt 8th DAN'), ('black_9', 'Black Belt 9th DAN')], default='white', max_length=20)),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('emergency_contact', models.CharField(max_length=15)),
                ('emergency_name', models.CharField(max_length=100)),
                ('medical_conditions', models.TextField(blank=True)),
                ('blood_type', models.CharField(blank=True, max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.school')),
            ],
        ),
    ]
