# Generated by Django 6.0.3 on 2026-03-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='fee_type',
            field=models.CharField(choices=[('monthly', 'Monthly Fee'), ('grading', 'Grading Fee'), ('uniform', 'Uniform'), ('tshirt', 'T-Shirt'), ('tournament', 'Tournament'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fee',
            name='month',
            field=models.DateField(blank=True, help_text='For monthly fees (first day of month)', null=True),
        ),
    ]
