# Generated by Django 6.0.3 on 2026-04-07 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subdomain', models.SlugField(help_text="e.g., 'taiping', 'ipoh', 'klang'", unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='club_logos/')),
                ('primary_color', models.CharField(default='#007bff', help_text='Brand color (hex code)', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', help_text='Secondary brand color', max_length=7)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subscription_tier', models.CharField(choices=[('free', 'Free Trial'), ('basic', 'Basic ($10/mo)'), ('pro', 'Pro ($20/mo)'), ('enterprise', 'Enterprise ($35/mo)')], default='free', max_length=20)),
                ('max_students', models.IntegerField(default=50, help_text='Maximum students allowed')),
                ('subscription_expiry', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Coach Ali, Admin Office', max_length=100)),
                ('role', models.CharField(help_text='e.g., Head Coach, Admin', max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_emergency', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='schools.club')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='schools.club')),
            ],
            options={
                'unique_together': {('club', 'code'), ('club', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('belt_level', models.CharField(help_text='e.g., White - Yellow, All Belts', max_length=50)),
                ('instructor', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schools.club')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('club_admin', 'Club Admin'), ('coach', 'Coach'), ('assistant_coach', 'Assistant Coach')], default='assistant_coach', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('club', models.ForeignKey(blank=True, help_text='Which club this user belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='schools.club')),
                ('schools', models.ManyToManyField(blank=True, help_text='Schools this user can access', to='schools.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
