# Generated by Django 6.0.3 on 2026-03-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
